os: linux
sudo: required
language: generic

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded
  - arm-none-eabi-gcc --version

script:
  - make all -f makefile.gnucc
